services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
      DSN:  "postgres://makhmud:1@db/visitca?sslmode=disable"
      TOKEN_TIME: "30"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: [ "redis-server", "--dbfilename", "redis_dump.rdb" ]


volumes:
  postgres_data:
